version: '3'
services:
  test:
    build: .
    command: tests/ntio_sockets_test

  gdb_server:
    build: docker/gdb_server
    ports:
      - "7773:22"

  cpplint_src:
    build: docker/cpplint
    command: bash -c "find src/ -name "*.cc" -o -name "*.h"  | xargs cpplint.py"
    volumes:
      - .:/app/

  cpplint_examples:
    build: docker/cpplint
    command: bash -c "find examples/ -name "*.cc" -o -name "*.h"  | xargs cpplint.py"
    volumes:
      - .:/app/
