name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cpplint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check code in /src
        run: docker-compose run cpplint_src
      - name: Check code in /examples
        run: docker-compose run cpplint_examples

  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build code in Docker
        run: docker-compose build test
      - name: Run tests
        run: docker-compose run test